### ISSUE TITLE
Problem using ASM golay decoder

### ISSUE THREAD

**Issue by mexsat** [mndza/gr-sattools#6]
Hi. I have created a .grc file to decode using the ASM golay decoder. 
I have installed gr-sattools and GNU in two different computers, the first one using Linux Ubuntu Mate (18.04) and the other using Linux Ubuntu Xenial 16.04. 
The one with Ubuntu Mate works fine but the other gives me the following message:
(python2:12200): IBUS-WARNING **: The owner of /home/<user>/.config/ibus/bus is not <user>!
gr::log :DEBUG: correlate_access_code_tag_bb0 - Access code: 930b51de
gr::log :DEBUG: correlate_access_code_tag_bb0 - Mask: ffffffff
gr::log :DEBUG: correlate_access_code_tag_bb0 - writing tag at sample 45706

>>> Done

Any suggestion for this?
Thank you

**Comment by mndza** [comment]
Hi,

Do these messages prevent you from running the flowgraph?

The IBUS-WARNING seems like a permissions problem which is not related to gr-sattools, are you running GNURadio Companion as root?

The other messages (DEBUG) are expected if [logging](https://wiki.gnuradio.org/index.php/Logging) is set to include them, which may be the default case due to the different versions. In any case, they can be disabled.
